export const DOGS = [
    { name: "La China", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Mestizo", Tamano: "Grande", personalidad: ["Tranquilo", "Alegre", "Hambriento"], img: "resources/chinese_3.jpg", sexo: "Macho", color: "Cafe", edad: "5 años", id: 9 },
    { name: "El loco matias", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Golden", Tamano: "Grande", personalidad: ["Jugueton"], img: "resources/prueba2.png", sexo: "Hembra", color: "Blanco", edad: "3 años", id: 8 },
    { name: "Rafa (El)", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Golden", Tamano: "Grande", personalidad: ["Jugueton"], img: "resources/rafa.png", sexo: "Macho", color: "Cafe", edad: "3 años", id: 12 },

    { name: "Filis el perro feliz", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Golden", Tamano: "Mediano", personalidad: ["Enojado"], img: "resources/prueba3.png", sexo: "Macho", color: "Blanco", edad: "3 años", id: 7 },
    { name: "Jotchua", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Golden", Tamano: "Chico", personalidad: ["Triste"], img: "resources/prueba4.png", sexo: "Macho", color: "Dorado", edad: "2 años", id: 6 },
];

export const CATS = [
    { name: "Ñango", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Naranja", Tamano: "Mediano", personalidad: ["Enojado","Feroz"], img: "resources/cat_orange_angry.gif", sexo: "Hembra", color: "Naranja", edad: "9 años", id: 5 },
    { name: "Flabio", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Naranja", Tamano: "Chico", personalidad: ["Loco"], img: "resources/crunchy_cat_2.jpg", sexo: "Macho", color: "Blanco", edad: "9 años", id: 4 },
    { name: "FlipFloppa", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Rojo", Tamano: "Grande", personalidad: ["Alegre"], img: "resources/big-floppa-mad-floppa.gif", sexo: "Macho", color: "Naranja", edad: "1 años", id: 3 },
];

export const OTHERS = [
    { name: "Yuan", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", raza: "Tortuga", Tamano: "Chico", personalidad: ["Tranquilo"], img: "resources/turti.png", sexo: "Macho", color: "Verde", edad: "5 años", id: 2 },
];

export const PETS = [].concat(DOGS, CATS, OTHERS);